### ISSUE TITLE
Error during building with FFMPEG 3.2

### ISSUE THREAD

**Issue by flyonme** [realrainer/avrmodule#1]
Hello,

I have the following error during build:

```
../astreamdecode.cpp: In function 'void aStreamDecodeThread(uv_work_t*)':
../astreamdecode.cpp:45:22: error: 'PIX_FMT_YUV420P' was not declared in this scope
         c->pix_fmt = PIX_FMT_YUV420P;
```

I think that it's due to updated version of ffmpeg. Could you advice?

**Comment by realrainer** [comment]
Hello, I fixed this issue by this commit:
https://github.com/realrainer/avrmodule/commit/e0ed690e273eb184cf0dd386149f0eb262b71428
